Translate starting-a-project.md
open-craft-guild/open-source-guide pull request #21
Opened 2017-03-04 05:32 UTC by numrut

Resolves #16

2017-03-04 16:20 UTC, anxolerd reviewed
Якось так.
Можу і помилятися. Якщо десь помиляюся -- буду вдячний, якщо вкажете на це)

2017-03-04 16:20 UTC, anxolerd commented on _articles/uk-UA/starting-a-project.md
> +  запуск-вашого-власного-open-source-проекту: "Запуск вашого власного open source проекту"
ІМХО, "вашого" тут не потрібно

2017-03-04 16:20 UTC, anxolerd commented on _articles/uk-UA/starting-a-project.md
> +Отже ви роздумуєте над початком роботи з open source? Вітаємо! Світ цінує ваш внесок. Давайте поговоримо про те, що таке open source та чому люди цим займаються.
Кома після "отже"

2017-03-04 16:20 UTC, anxolerd commented on _articles/uk-UA/starting-a-project.md
> +* Один з друзів, кондитер, пропонує зменшити кількість цукру (_зміна_)
Один **із** друзів

2017-03-04 16:20 UTC, anxolerd commented on _articles/uk-UA/starting-a-project.md
> +Для порівняння, цей процес з closed source проектом виглядав би як похід у ресторан та замовлення шматочку вишневого пирога. Ви маєте платити за те щоб скуштувати пирога і ресторан навряд чи дасть ва
За те **кома** щоб скуштувати пирога **кома**

2017-03-04 16:20 UTC, anxolerd commented on _articles/uk-UA/starting-a-project.md
> +**Якщо ви частина компанії, що займається open source проектом,** упевніться що ваш проект володіє внутрішніми ресурсами достатніми для процвітання. Вам знадобиться визначити хто опікуватиметься прое
визначити **кома** хто опікуватиметься проектом після запуску **кома** та як ви ...

2017-03-04 16:20 UTC, anxolerd commented on _articles/uk-UA/starting-a-project.md
> +Загалом, ви маєте відкривати свій проект коли почуваєтесь готовими до перегляду вашої роботи іншими людьми та їхнії відгуків.
опечатка у слові _їхні**х**_

2017-03-04 16:20 UTC, anxolerd commented on _articles/uk-UA/starting-a-project.md
> +Іноді, люди уникають написання README, бо вважають проект незавершеним, або не бажають отримувати внески інших. Це, натомість, дуже хороші приводи написати його.
Я б сказав _Навпаки, це дуже хороші причини, аби написати його_. Але це так, ІМХО.

2017-03-04 16:20 UTC, anxolerd commented on _articles/uk-UA/starting-a-project.md
> +Як і у випадку з open source ліцензіями, існують також певні стандарти для кодексу честі, тож вам не потрібно писати все з нуля. [Contributor Covenant](http://contributor-covenant.org/) це кодекс чес
використовується [...] проект**ами**
Але, ІМХО, тут краще пефразувати: _кодекс честі, який використову**ють** понад 40,000 open source проектів_

2017-03-04 19:52 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +**Якщо ви частина компанії, що займається open source проектом,** упевніться що ваш проект володіє внутрішніми ресурсами достатніми для процвітання. Вам знадобиться визначити хто опікуватиметься прое
ось тут не впевнений. мабуть без ком. це не вставне словосполученні, бо при викиданні його з речення втрачається частина сенсу.

2017-03-04 19:54 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Як і у випадку з open source ліцензіями, існують також певні стандарти для кодексу честі, тож вам не потрібно писати все з нуля. [Contributor Covenant](http://contributor-covenant.org/) це кодекс чес
`більше, ніж` -> `понад`

2017-03-04 19:55 UTC, webknjaz commented
@numrut please rebase your branch

2017-03-04 23:26 UTC, webknjaz requested changes
Осилив рев'ю до рядка 50, пізніше продовжу. Поки можеш прикинути що будеш правити + ребейзнути цю гілку.

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +  що-таке-open-source-та-навіщо-він-потрібен: "Що таке open source та навіщо він потрібен"
Ключі з великої літери.

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +description: Дізнайтесь більше про світ open source та будьте готові до запуску власного проекту.
Дізнайтес**я**

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Отже ви роздумуєте над початком роботи з open source? Вітаємо! Світ цінує ваш внесок. Давайте поговоримо про те, що таке open source та чому люди цим займаються.
*розмірковуєте*

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +### Шо означає "open source"?
**Щ**о

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Коли проект є open source, то це означає, що **будь-хто може переглядати, використовувати, змінювати та поширювати ваш проект з будь-якою метою.** Ці дозволи забезпечуються [open source ліцензією](ht
Може "права"? (не впевнений)

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Open source є потужним, бо він знижує перешкоди на шляху впровадження, дозволяючи ідеям поширюватись швидше.
поширюватис**я**

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* Кожен пробує пиріг (_використання_)
*куштує*

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* Пиріг стає хітом! Друзі просять у вас рецепт і ви його даєте (_перегляд_)
*ним ділитеся* [рецептом]

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* Інший товариш просить дозволу використати це для обіду на наступному тижні (_поширення_)
Там же в оригіналі "подруга Ліза, яка просить скористатися ним на вечері наступного тижня"
(dinner це вечеря в англомовному світі, то лише в радянській версії англійської прижилося як обід)

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Для порівняння, цей процес з closed source проектом виглядав би як похід у ресторан та замовлення шматочку вишневого пирога. Ви маєте платити за те щоб скуштувати пирога і ресторан навряд чи дасть ва
> процес **i**з

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Для порівняння, цей процес з closed source проектом виглядав би як похід у ресторан та замовлення шматочку вишневого пирога. Ви маєте платити за те щоб скуштувати пирога і ресторан навряд чи дасть ва
> **за**платити

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Для порівняння, цей процес з closed source проектом виглядав би як похід у ресторан та замовлення шматочку вишневого пирога. Ви маєте платити за те щоб скуштувати пирога і ресторан навряд чи дасть ва
> під своїм іменем

мабуть "від свого імені" чи "з іншою назвою"

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +[Існує чимало причин](http://ben.balter.com/2015/11/23/why-open-source/), через які особа чи організація можуть захотіти зробити свій проект open source. Ось деякі приклади:
> Ось деякі приклади:

Ось деякі з них:

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +  Однією з найкорисніших речей у плані набутого досвіду, що я отримав від використання та співпраці в open source, стали взамємовідносини з іншими розробниками, які стикаються з тими ж проблемами що
Давай отак:

> Використовуючи та співпрацюючи над проектами в open source, я будую зв'язки з іншими розробниками, які мають такі ж проблеми, як і я, і це дає мені чи не найцінніший життєвий досвід.

(c) @bluebirrrrd

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +— @kentcdodds, ["How getting into Open Source has been awesome for me"](https://medium.com/@kentcdodds/how-getting-into-open-source-has-been-awesome-for-me-8480cd756a80#.pjt9oqp4w)
> Чим потрапляння до open source дивовижне для мене

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* **Співпраця:** Open source проекти можуть приймати зміни від будь-кого у світі. Наприклад, [Exercism](https://github.com/exercism/), це платформа для вправляння у програмуванні з більш, ніж 350 уча
> exercism

з малої літери

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* **Співпраця:** Open source проекти можуть приймати зміни від будь-кого у світі. Наприклад, [Exercism](https://github.com/exercism/), це платформа для вправляння у програмуванні з більш, ніж 350 уча
> з більш, ніж 350 учасниками

звучить ніби 350 людей виконують вправи з програмування. треба вигадати щось краще з цими "вкладниками", "дописувачами" чи "членами". як мінімум структуру речення змінити

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* **Запозичення та переосмислення:** Open source проекти можуть бути використані будь-ким і майже з будь-якою метою. Люди можуть навіть використовувати ці проекти для побудови інших. Наприклад, [Word
> майже з

може "з майже"?

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* **Запозичення та переосмислення:** Open source проекти можуть бути використані будь-ким і майже з будь-якою метою. Люди можуть навіть використовувати ці проекти для побудови інших. Наприклад, [Word
> Люди можуть навіть використовувати ці проекти для побудови інших.

мабуть "для створення інших речей", бо там не сказано що саме інших проектів.

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* **Запозичення та переосмислення:** Open source проекти можуть бути використані будь-ким і майже з будь-якою метою. Люди можуть навіть використовувати ці проекти для побудови інших. Наприклад, [Word
https://github.com/progit/progit2-uk/issues/143

не певен, може дійсно "форк" лишити

2017-03-04 23:26 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* **Запозичення та переосмислення:** Open source проекти можуть бути використані будь-ким і майже з будь-якою метою. Люди можуть навіть використовувати ці проекти для побудови інших. Наприклад, [Word
> під назвою

оце зайве

2017-03-06 14:07 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Як і у випадку з open source ліцензіями, існують також певні стандарти для кодексу честі, тож вам не потрібно писати все з нуля. [Contributor Covenant](http://contributor-covenant.org/) це кодекс чес
> що використовують

який використовують

2017-03-06 14:08 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* Інший товариш просить дозволу використати це для вечері на наступному тижні (_поширення_)
А де Ліза?

2017-03-06 14:17 UTC, numrut commented on _articles/uk-UA/starting-a-project.md
> +* Інший товариш просить дозволу використати це для вечері на наступному тижні (_поширення_)
Вирішив, що це не обов’язково.

2017-03-06 14:18 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* Інший товариш просить дозволу використати це для вечері на наступному тижні (_поширення_)
я думаю, що варто ближче до оригіналу перекладати через те, що одні й ті ж персонажі можуть повторюватися в подальшому, наприклад

2017-03-06 14:25 UTC, numrut commented on _articles/uk-UA/starting-a-project.md
> +* Інший товариш просить дозволу використати це для вечері на наступному тижні (_поширення_)
Згоден. Але це не той випадок. Навпаки, виникає питання "яка ще Ліза? до чого вона тут?"

2017-03-06 14:31 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* Інший товариш просить дозволу використати це для вечері на наступному тижні (_поширення_)
там же ж написано, що подруга вроді

2017-03-06 14:39 UTC, numrut commented on _articles/uk-UA/starting-a-project.md
> +* Інший товариш просить дозволу використати це для вечері на наступному тижні (_поширення_)
в цьому контексті її ім’я не має значення

2017-03-06 14:40 UTC, numrut commented on _articles/uk-UA/starting-a-project.md
> +* Інший товариш просить дозволу використати це для вечері на наступному тижні (_поширення_)
схоже, це найбільш важлива проблема в перекладі гайду))

2017-03-06 19:37 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* Інший товариш просить дозволу використати це для вечері на наступному тижні (_поширення_)
я не хочу неточностей ніде

2017-03-07 12:42 UTC, kateGlebova commented on _articles/uk-UA/starting-a-project.md
> +**Якщо ви частина компанії, що займається open source проектом,** упевніться що ваш проект володіє внутрішніми ресурсами достатніми для процвітання. Вам знадобиться визначити хто опікуватиметься прое
це складносурядне речення. тут потрібні коми, меня здається

2018-01-21 00:16 UTC, oksankashyshka commented on _articles/uk-UA/starting-a-project.md
> +  Запуск-вашого-власного-open-source-проекту: "Запуск вашого власного open source проекту"
Можливо, просто "Запуск власного..." ?

2018-01-21 07:02 UTC, webknjaz requested changes

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* Інший товариш просить дозволу використати це для обіду на наступному тижні (_поширення_)
Lisa

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* **Прозорість:** Кожен може оглядати open source проект для пошуку помилок чи невідповідностей. Прозорість має значання для урядів таких країн, як от [Болгарія](https://medium.com/@bozhobg/bulgaria-
> оглядати

перевіряти наявність

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +* **Прозорість:** Кожен може оглядати open source проект для пошуку помилок чи невідповідностей. Прозорість має значання для урядів таких країн, як от [Болгарія](https://medium.com/@bozhobg/bulgaria-
> на зразок

на кшталт

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Варто зазначити, що Open source це не тільки для програмного забезпечення. Ви можете зробити open source усе що завгодно, від наборів даних до книжок. Ознайомтесь з [GitHub Explore](https://github.co
> Open source

open source —

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Через те, що [open source ліцензія вимагає](https://opensource.org/osd-annotated) щоб кожен міг використовувати, змінювати та ділитись вашим проектом з довільними намірами, проекти, як правило, є без
> з довільними намірами

майже

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Через те, що [open source ліцензія вимагає](https://opensource.org/osd-annotated) щоб кожен міг використовувати, змінювати та ділитись вашим проектом з довільними намірами, проекти, як правило, є без
> use the free version instead

користуватися вільною версією замість цього

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Коротка відповідь — так, тому що не залежно від результату, запуск власного проекту це чудовий спосіб зрозуміти як працює open source.
> не залежно

незалежно

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Якщо ви ніколи не мали open source проекта до цього, то можете нервувати з приводу того що скажуть інші, або чи взагалі хтось це помітить. Якщо звучить знайомо, ви не одні!
> одні

самі

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Open source робота це як і будь яка інша творча діяльність, як письмо чи живопис. Поділитись своєю працею з усім світом може бути лячно, але практикуватись — це єдиний спосіб стати краще, навіть якщо
> Open source робота це як і будь яка інша творча діяльність, як письмо чи живопис.

Робота над open source подібна до будь-якої іншої творчої діяльності, на кшталт письменництва чи малювання.

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +Цілі можуть допомогти вам усвідомити над чим працювати, чому сказати «ні», або де вам знадобиться стороння допомога. Почніть з запитання до себе: _чому я роблю цей проект open source?_
лапки

2018-01-21 07:02 UTC, webknjaz commented on _articles/uk-UA/starting-a-project.md
> +  Запуск-вашого-власного-open-source-проекту: "Запуск вашого власного open source проекту"
Ага, як мінімум "свого"

2021-10-16 09:23 UTC, closed without merging